#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from new.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "new.y"

#include <bits/stdc++.h>
#include "symbtab.hpp"

extern FILE *yyin, *tokfile, *parsefile ;
extern int yylineno;
int yylex();
void yyerror(char *s);

#line 11 "new.y"
typedef union {
  char * string;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INTEGER_CONSTANT	258
#define	STRING_CONSTANT	259
#define	FLOAT_CONSTANT	260
#define	TRUE	261
#define	FALSE	262
#define	INT	263
#define	DOUBLE	264
#define	STRING	265
#define	BOOL	266
#define	MASS	267
#define	TIME	268
#define	POSITION	269
#define	VELOCITY	270
#define	ACC	271
#define	ENERGY	272
#define	THETA	273
#define	E	274
#define	DISTANCE	275
#define	MOMENTUM	276
#define	ID	277
#define	INPUT	278
#define	OUTPUT	279
#define	SETR	280
#define	ADDR	281
#define	SETV	282
#define	ADDV	283
#define	SETA	284
#define	ADDA	285
#define	SETP	286
#define	GETR	287
#define	GETA	288
#define	GETV	289
#define	KE_AFTER	290
#define	PE_AFTER	291
#define	TE_AFTER	292
#define	ANGLE_AFTER	293
#define	V_AFTER	294
#define	R_AFTER	295
#define	GET_TRAJ	296
#define	COLLIDE	297
#define	TIME_TO_COLLIDE	298
#define	ROC_AFTER	299
#define	P_AFTER	300
#define	S_AFTER	301
#define	TIME_TO_R	302
#define	TIME_TO_V	303
#define	LOOP	304
#define	BREAK	305
#define	START	306
#define	SIN	307
#define	COS	308
#define	TAN	309
#define	MAG	310
#define	OPENCC	311
#define	CLOSECC	312
#define	OPENSQ	313
#define	CLOSESQ	314
#define	OPENCU	315
#define	CLOSECU	316
#define	DOLLAR	317
#define	DOT	318
#define	DOUBLE_QUOTE	319
#define	SINGLE_QUOTE	320
#define	COMMA	321
#define	COLON	322
#define	ARROW	323
#define	ADD	324
#define	SUB	325
#define	MUL	326
#define	DIV	327
#define	MOD	328
#define	EXP	329
#define	EQ	330
#define	NEQ	331
#define	GEQ	332
#define	LEQ	333
#define	GT	334
#define	LT	335
#define	LOGICOP	336
#define	UNIOP	337
#define	UNINEG	338
#define	ASSGN	339
#define	DARR	340
#define	CMT	341
#define	QUESTION	342
#define	NON_NEGATIVE_INT	343
#define	FIRST	344
#define	SECOND	345
#define	OTHERWISE	346
#define	SCOPEOPEN	347
#define	SCOPECLOSE	348


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INTEGER_CONSTANT;
static const int STRING_CONSTANT;
static const int FLOAT_CONSTANT;
static const int TRUE;
static const int FALSE;
static const int INT;
static const int DOUBLE;
static const int STRING;
static const int BOOL;
static const int MASS;
static const int TIME;
static const int POSITION;
static const int VELOCITY;
static const int ACC;
static const int ENERGY;
static const int THETA;
static const int E;
static const int DISTANCE;
static const int MOMENTUM;
static const int ID;
static const int INPUT;
static const int OUTPUT;
static const int SETR;
static const int ADDR;
static const int SETV;
static const int ADDV;
static const int SETA;
static const int ADDA;
static const int SETP;
static const int GETR;
static const int GETA;
static const int GETV;
static const int KE_AFTER;
static const int PE_AFTER;
static const int TE_AFTER;
static const int ANGLE_AFTER;
static const int V_AFTER;
static const int R_AFTER;
static const int GET_TRAJ;
static const int COLLIDE;
static const int TIME_TO_COLLIDE;
static const int ROC_AFTER;
static const int P_AFTER;
static const int S_AFTER;
static const int TIME_TO_R;
static const int TIME_TO_V;
static const int LOOP;
static const int BREAK;
static const int START;
static const int SIN;
static const int COS;
static const int TAN;
static const int MAG;
static const int OPENCC;
static const int CLOSECC;
static const int OPENSQ;
static const int CLOSESQ;
static const int OPENCU;
static const int CLOSECU;
static const int DOLLAR;
static const int DOT;
static const int DOUBLE_QUOTE;
static const int SINGLE_QUOTE;
static const int COMMA;
static const int COLON;
static const int ARROW;
static const int ADD;
static const int SUB;
static const int MUL;
static const int DIV;
static const int MOD;
static const int EXP;
static const int EQ;
static const int NEQ;
static const int GEQ;
static const int LEQ;
static const int GT;
static const int LT;
static const int LOGICOP;
static const int UNIOP;
static const int UNINEG;
static const int ASSGN;
static const int DARR;
static const int CMT;
static const int QUESTION;
static const int NON_NEGATIVE_INT;
static const int FIRST;
static const int SECOND;
static const int OTHERWISE;
static const int SCOPEOPEN;
static const int SCOPECLOSE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INTEGER_CONSTANT=258
	,STRING_CONSTANT=259
	,FLOAT_CONSTANT=260
	,TRUE=261
	,FALSE=262
	,INT=263
	,DOUBLE=264
	,STRING=265
	,BOOL=266
	,MASS=267
	,TIME=268
	,POSITION=269
	,VELOCITY=270
	,ACC=271
	,ENERGY=272
	,THETA=273
	,E=274
	,DISTANCE=275
	,MOMENTUM=276
	,ID=277
	,INPUT=278
	,OUTPUT=279
	,SETR=280
	,ADDR=281
	,SETV=282
	,ADDV=283
	,SETA=284
	,ADDA=285
	,SETP=286
	,GETR=287
	,GETA=288
	,GETV=289
	,KE_AFTER=290
	,PE_AFTER=291
	,TE_AFTER=292
	,ANGLE_AFTER=293
	,V_AFTER=294
	,R_AFTER=295
	,GET_TRAJ=296
	,COLLIDE=297
	,TIME_TO_COLLIDE=298
	,ROC_AFTER=299
	,P_AFTER=300
	,S_AFTER=301
	,TIME_TO_R=302
	,TIME_TO_V=303
	,LOOP=304
	,BREAK=305
	,START=306
	,SIN=307
	,COS=308
	,TAN=309
	,MAG=310
	,OPENCC=311
	,CLOSECC=312
	,OPENSQ=313
	,CLOSESQ=314
	,OPENCU=315
	,CLOSECU=316
	,DOLLAR=317
	,DOT=318
	,DOUBLE_QUOTE=319
	,SINGLE_QUOTE=320
	,COMMA=321
	,COLON=322
	,ARROW=323
	,ADD=324
	,SUB=325
	,MUL=326
	,DIV=327
	,MOD=328
	,EXP=329
	,EQ=330
	,NEQ=331
	,GEQ=332
	,LEQ=333
	,GT=334
	,LT=335
	,LOGICOP=336
	,UNIOP=337
	,UNINEG=338
	,ASSGN=339
	,DARR=340
	,CMT=341
	,QUESTION=342
	,NON_NEGATIVE_INT=343
	,FIRST=344
	,SECOND=345
	,OTHERWISE=346
	,SCOPEOPEN=347
	,SCOPECLOSE=348


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INTEGER_CONSTANT=258;
const int YY_parse_CLASS::STRING_CONSTANT=259;
const int YY_parse_CLASS::FLOAT_CONSTANT=260;
const int YY_parse_CLASS::TRUE=261;
const int YY_parse_CLASS::FALSE=262;
const int YY_parse_CLASS::INT=263;
const int YY_parse_CLASS::DOUBLE=264;
const int YY_parse_CLASS::STRING=265;
const int YY_parse_CLASS::BOOL=266;
const int YY_parse_CLASS::MASS=267;
const int YY_parse_CLASS::TIME=268;
const int YY_parse_CLASS::POSITION=269;
const int YY_parse_CLASS::VELOCITY=270;
const int YY_parse_CLASS::ACC=271;
const int YY_parse_CLASS::ENERGY=272;
const int YY_parse_CLASS::THETA=273;
const int YY_parse_CLASS::E=274;
const int YY_parse_CLASS::DISTANCE=275;
const int YY_parse_CLASS::MOMENTUM=276;
const int YY_parse_CLASS::ID=277;
const int YY_parse_CLASS::INPUT=278;
const int YY_parse_CLASS::OUTPUT=279;
const int YY_parse_CLASS::SETR=280;
const int YY_parse_CLASS::ADDR=281;
const int YY_parse_CLASS::SETV=282;
const int YY_parse_CLASS::ADDV=283;
const int YY_parse_CLASS::SETA=284;
const int YY_parse_CLASS::ADDA=285;
const int YY_parse_CLASS::SETP=286;
const int YY_parse_CLASS::GETR=287;
const int YY_parse_CLASS::GETA=288;
const int YY_parse_CLASS::GETV=289;
const int YY_parse_CLASS::KE_AFTER=290;
const int YY_parse_CLASS::PE_AFTER=291;
const int YY_parse_CLASS::TE_AFTER=292;
const int YY_parse_CLASS::ANGLE_AFTER=293;
const int YY_parse_CLASS::V_AFTER=294;
const int YY_parse_CLASS::R_AFTER=295;
const int YY_parse_CLASS::GET_TRAJ=296;
const int YY_parse_CLASS::COLLIDE=297;
const int YY_parse_CLASS::TIME_TO_COLLIDE=298;
const int YY_parse_CLASS::ROC_AFTER=299;
const int YY_parse_CLASS::P_AFTER=300;
const int YY_parse_CLASS::S_AFTER=301;
const int YY_parse_CLASS::TIME_TO_R=302;
const int YY_parse_CLASS::TIME_TO_V=303;
const int YY_parse_CLASS::LOOP=304;
const int YY_parse_CLASS::BREAK=305;
const int YY_parse_CLASS::START=306;
const int YY_parse_CLASS::SIN=307;
const int YY_parse_CLASS::COS=308;
const int YY_parse_CLASS::TAN=309;
const int YY_parse_CLASS::MAG=310;
const int YY_parse_CLASS::OPENCC=311;
const int YY_parse_CLASS::CLOSECC=312;
const int YY_parse_CLASS::OPENSQ=313;
const int YY_parse_CLASS::CLOSESQ=314;
const int YY_parse_CLASS::OPENCU=315;
const int YY_parse_CLASS::CLOSECU=316;
const int YY_parse_CLASS::DOLLAR=317;
const int YY_parse_CLASS::DOT=318;
const int YY_parse_CLASS::DOUBLE_QUOTE=319;
const int YY_parse_CLASS::SINGLE_QUOTE=320;
const int YY_parse_CLASS::COMMA=321;
const int YY_parse_CLASS::COLON=322;
const int YY_parse_CLASS::ARROW=323;
const int YY_parse_CLASS::ADD=324;
const int YY_parse_CLASS::SUB=325;
const int YY_parse_CLASS::MUL=326;
const int YY_parse_CLASS::DIV=327;
const int YY_parse_CLASS::MOD=328;
const int YY_parse_CLASS::EXP=329;
const int YY_parse_CLASS::EQ=330;
const int YY_parse_CLASS::NEQ=331;
const int YY_parse_CLASS::GEQ=332;
const int YY_parse_CLASS::LEQ=333;
const int YY_parse_CLASS::GT=334;
const int YY_parse_CLASS::LT=335;
const int YY_parse_CLASS::LOGICOP=336;
const int YY_parse_CLASS::UNIOP=337;
const int YY_parse_CLASS::UNINEG=338;
const int YY_parse_CLASS::ASSGN=339;
const int YY_parse_CLASS::DARR=340;
const int YY_parse_CLASS::CMT=341;
const int YY_parse_CLASS::QUESTION=342;
const int YY_parse_CLASS::NON_NEGATIVE_INT=343;
const int YY_parse_CLASS::FIRST=344;
const int YY_parse_CLASS::SECOND=345;
const int YY_parse_CLASS::OTHERWISE=346;
const int YY_parse_CLASS::SCOPEOPEN=347;
const int YY_parse_CLASS::SCOPECLOSE=348;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		382
#define	YYFLAG		-32768
#define	YYNTBASE	94

#define YYTRANSLATE(x) ((unsigned)(x) <= 348 ? yytranslate[x] : 161)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    66,    67,    68,    69,    70,    71,    72,    73,    74,    75,
    76,    77,    78,    79,    80,    81,    82,    83,    84,    85,
    86,    87,    88,    89,    90,    91,    92,    93
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     9,    11,    12,    18,    21,    24,
    27,    30,    34,    37,    40,    43,    46,    47,    48,    49,
    58,    61,    64,    67,    70,    73,    76,    80,    83,    86,
    89,    92,    93,    94,    95,   104,   107,   110,   114,   116,
   118,   120,   122,   124,   126,   128,   130,   132,   134,   136,
   138,   144,   146,   148,   150,   152,   154,   156,   158,   160,
   162,   164,   166,   168,   170,   172,   174,   176,   178,   180,
   183,   187,   192,   197,   199,   201,   203,   205,   207,   209,
   211,   213,   215,   217,   219,   221,   224,   228,   232,   234,
   238,   242,   247,   252,   257,   259,   261,   263,   266,   269,
   273,   277,   279,   281,   284,   286,   289,   291,   294,   298,
   303,   305,   309,   314,   320,   324,   325,   326,   336,   337,
   346,   347,   357,   360,   363,   367,   370,   372,   377,   382,
   386,   388,   391,   393,   395,   397,   399,   401,   403,   405,
   407,   409,   414,   419,   427,   435,   443,   448,   456,   464,
   472,   477,   485,   493,   501,   506,   514,   522,   530,   538,
   548,   556,   564,   572,   580,   588,   598,   608,   610,   612,
   616,   620,   622,   626,   628,   630,   631,   632,   645,   646,
   647,   659,   662,   663
};

static const short yyrhs[] = {    95,
     0,    94,    95,     0,   134,     0,    96,     0,   154,     0,
     0,    51,    60,    97,    98,    61,     0,   113,    98,     0,
   122,    98,     0,   126,    98,     0,   129,    98,     0,   132,
    63,    98,     0,   133,    98,     0,   134,    98,     0,   135,
    98,     0,   136,    98,     0,     0,     0,     0,    92,    99,
    60,    98,    93,   100,    61,    98,     0,   138,    98,     0,
   150,    98,     0,   113,   101,     0,   122,   101,     0,   126,
   101,     0,   129,   101,     0,   132,    63,   101,     0,   133,
   101,     0,   134,   101,     0,   135,   101,     0,   136,   101,
     0,     0,     0,     0,    92,   102,    60,   101,    93,   103,
    61,    98,     0,   138,   101,     0,   150,   101,     0,    50,
    63,   101,     0,    69,     0,    70,     0,    71,     0,    72,
     0,    73,     0,    74,     0,    75,     0,    76,     0,    77,
     0,    79,     0,    78,     0,    80,     0,    58,   119,    66,
   119,    59,     0,     8,     0,     9,     0,    11,     0,    10,
     0,    12,     0,    13,     0,    14,     0,    15,     0,    16,
     0,    17,     0,    18,     0,    19,     0,    20,     0,    21,
     0,   107,     0,   108,     0,    22,     0,   110,     0,   110,
   112,     0,    58,   119,    59,     0,    58,   119,    59,   112,
     0,   111,    84,   119,    63,     0,    89,     0,    90,     0,
    22,     0,   111,     0,    88,     0,     3,     0,     5,     0,
     4,     0,     6,     0,     7,     0,   123,     0,   106,     0,
    83,   116,     0,   123,    68,   114,     0,   139,    68,   114,
     0,   139,     0,   106,    68,   114,     0,   115,    68,   114,
     0,    52,    56,   116,    57,     0,    53,    56,   116,    57,
     0,    54,    56,   116,    57,     0,   104,     0,    81,     0,
   105,     0,   120,   116,     0,   116,   121,     0,   118,   117,
   119,     0,   116,   117,   119,     0,   118,     0,   116,     0,
   120,    56,     0,    56,     0,   121,    57,     0,    57,     0,
   123,    63,     0,   115,    60,    61,     0,   115,    60,   124,
    61,     0,   119,     0,   119,    66,   124,     0,    58,   119,
    59,    60,     0,    58,   111,    82,    59,    60,     0,   125,
   101,    61,     0,     0,     0,   125,   101,    61,   127,    91,
    60,   128,   101,    61,     0,     0,    49,    58,   119,    59,
    60,   130,   101,    61,     0,     0,    49,    58,   111,    82,
    59,    60,   131,   101,    61,     0,   111,    82,     0,    83,
   119,     0,    85,   119,    63,     0,    85,    63,     0,    86,
     0,    24,    67,   119,    63,     0,    23,    67,   137,    63,
     0,   111,    66,   137,     0,   111,     0,   139,    63,     0,
   140,     0,   142,     0,   141,     0,   144,     0,   145,     0,
   146,     0,   147,     0,   143,     0,   148,     0,    55,    60,
   115,    61,     0,    55,    60,   106,    61,     0,    60,   115,
    61,    25,    60,   119,    61,     0,    60,   115,    61,    26,
    60,   119,    61,     0,    60,   115,    61,    40,    60,   119,
    61,     0,    60,   115,    61,    32,     0,    60,   115,    61,
    27,    60,   119,    61,     0,    60,   115,    61,    28,    60,
   119,    61,     0,    60,   115,    61,    39,    60,   119,    61,
     0,    60,   115,    61,    34,     0,    60,   115,    61,    31,
    60,   119,    61,     0,    60,   115,    61,    29,    60,   119,
    61,     0,    60,   115,    61,    30,    60,   119,    61,     0,
    60,   115,    61,    33,     0,    60,   115,    61,    35,    60,
   119,    61,     0,    60,   115,    61,    36,    60,   119,    61,
     0,    60,   115,    61,    37,    60,   119,    61,     0,    60,
   115,    61,    38,    60,   119,    61,     0,    60,   115,    61,
    42,    60,    22,    66,    22,    61,     0,    60,   115,    61,
    42,    60,    22,    61,     0,    60,   115,    61,    43,    60,
    22,    61,     0,    60,   115,    61,    46,    60,   119,    61,
     0,    60,   115,    61,    44,    60,   119,    61,     0,    60,
   115,    61,    45,    60,   119,    61,     0,    60,   115,    61,
    47,    60,   149,    66,   149,    61,     0,    60,   115,    61,
    48,    60,   149,    66,   149,    61,     0,   119,     0,    87,
     0,   109,   151,    63,     0,   152,    66,   151,     0,   152,
     0,   111,    84,   119,     0,   111,     0,    22,     0,     0,
     0,   109,   153,    84,    60,   159,    61,    85,    60,   155,
    98,   156,    61,     0,     0,     0,   109,   153,    84,    60,
    61,    85,    60,   157,    98,   158,    61,     0,   109,    22,
     0,     0,   109,    22,   160,    66,   159,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    56,    57,    60,    61,    62,    65,    65,    68,    69,    70,
    71,    72,    73,    74,    75,    76,    77,    78,    78,    78,
    79,    80,    83,    84,    85,    86,    87,    88,    89,    90,
    91,    92,    93,    93,    93,    94,    95,    96,    99,   100,
   101,   102,   103,   104,   107,   108,   109,   110,   111,   112,
   115,   118,   119,   120,   121,   124,   125,   126,   127,   128,
   129,   130,   131,   132,   133,   136,   137,   142,   153,   154,
   157,   158,   163,   166,   167,   170,   172,   173,   174,   175,
   176,   177,   178,   179,   180,   181,   182,   183,   184,   185,
   186,   187,   188,   189,   192,   193,   194,   197,   198,   200,
   201,   202,   203,   206,   207,   210,   211,   216,   219,   220,
   223,   224,   229,   230,   234,   235,   235,   235,   240,   240,
   241,   241,   246,   247,   252,   253,   258,   263,   268,   271,
   272,   277,   280,   281,   282,   283,   284,   285,   286,   287,
   288,   291,   292,   295,   296,   297,   298,   301,   302,   303,
   304,   307,   310,   311,   312,   315,   316,   317,   320,   323,
   324,   325,   328,   329,   330,   331,   332,   335,   336,   341,
   344,   345,   348,   349,   354,   356,   357,   361,   362,   363,
   368,   371,   376,   381
};

static const char * const yytname[] = {   "$","error","$illegal.","INTEGER_CONSTANT",
"STRING_CONSTANT","FLOAT_CONSTANT","TRUE","FALSE","INT","DOUBLE","STRING","BOOL",
"MASS","TIME","POSITION","VELOCITY","ACC","ENERGY","THETA","E","DISTANCE","MOMENTUM",
"ID","INPUT","OUTPUT","SETR","ADDR","SETV","ADDV","SETA","ADDA","SETP","GETR",
"GETA","GETV","KE_AFTER","PE_AFTER","TE_AFTER","ANGLE_AFTER","V_AFTER","R_AFTER",
"GET_TRAJ","COLLIDE","TIME_TO_COLLIDE","ROC_AFTER","P_AFTER","S_AFTER","TIME_TO_R",
"TIME_TO_V","LOOP","BREAK","START","SIN","COS","TAN","MAG","OPENCC","CLOSECC",
"OPENSQ","CLOSESQ","OPENCU","CLOSECU","DOLLAR","DOT","DOUBLE_QUOTE","SINGLE_QUOTE",
"COMMA","COLON","ARROW","ADD","SUB","MUL","DIV","MOD","EXP","EQ","NEQ","GEQ",
"LEQ","GT","LT","LOGICOP","UNIOP","UNINEG","ASSGN","DARR","CMT","QUESTION","NON_NEGATIVE_INT",
"FIRST","SECOND","OTHERWISE","SCOPEOPEN","SCOPECLOSE","code","code_subpart",
"startfn","@1","body","@2","@3","loop_body","@4","@5","bi_op","relop","vectors",
"primi_datatype","non_pri_datatype","datatypes","ID_singlevar","single_variable",
"dimensions","exp_stmt","pos","idadd","anything_with_value","operations","rhs_term",
"rhs_exp","openccs","closeccs","call_stmt_with_dot","call_stmt_without_dot",
"funccallargs","conditional_stmt_start","conditional_stmt","@6","@7","loop_stmt",
"@8","@9","unary_operation_without_dot","return_stmt","comments","output_stmt",
"input_stmt","ids","inbuilt_functions_with_dot","inbuilt_functions","rel_to_mag",
"rel_to_pos","rel_to_vel","rel_to_momentum","rel_to_acc","rel_to_energy","rel_to_angle",
"rel_to_collision","miscellaneous","term_misc","decl_stmt_with_exp","expressions",
"expression","idadd2","function_decl","@10","@11","@12","@13","parameters","@14",
""
};
#endif

static const short yyr1[] = {     0,
    94,    94,    95,    95,    95,    97,    96,    98,    98,    98,
    98,    98,    98,    98,    98,    98,    98,    99,   100,    98,
    98,    98,   101,   101,   101,   101,   101,   101,   101,   101,
   101,   101,   102,   103,   101,   101,   101,   101,   104,   104,
   104,   104,   104,   104,   105,   105,   105,   105,   105,   105,
   106,   107,   107,   107,   107,   108,   108,   108,   108,   108,
   108,   108,   108,   108,   108,   109,   109,   110,   111,   111,
   112,   112,   113,   114,   114,   115,   116,   116,   116,   116,
   116,   116,   116,   116,   116,   116,   116,   116,   116,   116,
   116,   116,   116,   116,   117,   117,   117,   118,   118,   119,
   119,   119,   119,   120,   120,   121,   121,   122,   123,   123,
   124,   124,   125,   125,   126,   127,   128,   126,   130,   129,
   131,   129,   132,   132,   133,   133,   134,   135,   136,   137,
   137,   138,   139,   139,   139,   139,   139,   139,   139,   139,
   139,   140,   140,   141,   141,   141,   141,   142,   142,   142,
   142,   143,   144,   144,   144,   145,   145,   145,   146,   147,
   147,   147,   148,   148,   148,   148,   148,   149,   149,   150,
   151,   151,   152,   152,   153,   155,   156,   154,   157,   158,
   154,   159,   160,   159
};

static const short yyr2[] = {     0,
     1,     2,     1,     1,     1,     0,     5,     2,     2,     2,
     2,     3,     2,     2,     2,     2,     0,     0,     0,     8,
     2,     2,     2,     2,     2,     2,     3,     2,     2,     2,
     2,     0,     0,     0,     8,     2,     2,     3,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     5,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     2,
     3,     4,     4,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     2,     3,     3,     1,     3,
     3,     4,     4,     4,     1,     1,     1,     2,     2,     3,
     3,     1,     1,     2,     1,     2,     1,     2,     3,     4,
     1,     3,     4,     5,     3,     0,     0,     9,     0,     8,
     0,     9,     2,     2,     3,     2,     1,     4,     4,     3,
     1,     2,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     4,     4,     7,     7,     7,     4,     7,     7,     7,
     4,     7,     7,     7,     4,     7,     7,     7,     7,     9,
     7,     7,     7,     7,     7,     9,     9,     1,     1,     3,
     3,     1,     3,     1,     1,     0,     0,    12,     0,     0,
    11,     2,     0,     5
};

static const short yydefact[] = {     0,
    52,    53,    55,    54,    56,    57,    58,    59,    60,    61,
    62,    63,    64,    65,     0,   127,     0,     1,     4,    66,
    67,     0,     3,     5,     6,     2,   175,     0,    17,     0,
    68,     0,     0,     0,     0,     0,     0,     0,     0,    18,
     0,     0,    69,     0,    17,     0,    17,     0,    32,    17,
    17,     0,    17,    17,    17,    17,    17,     0,   133,   135,
   134,   140,   136,   137,   138,   139,   141,    17,     0,     0,
     0,     0,     0,    79,    81,    80,    82,    83,     0,     0,
     0,   105,     0,     0,    78,    85,    77,     0,   103,   102,
     0,     0,    84,    89,    76,     0,    77,   124,   126,     0,
     0,     7,    68,   174,     0,   172,     0,    70,   123,     0,
     8,     0,     9,   108,     0,    33,     0,    32,    32,    32,
    32,     0,    32,    32,    32,    32,    32,    32,    10,    11,
    17,    13,    14,    15,    16,    21,   132,    22,     0,     0,
     0,   131,     0,     0,    77,     0,     0,     0,     0,     0,
     0,     0,    86,     0,     0,     0,   107,    39,    40,    41,
    42,    43,    44,    45,    46,    47,    49,    48,    50,    96,
    95,    97,     0,    99,     0,     0,   104,    98,     0,     0,
     0,   125,    17,     0,   170,     0,     0,     0,   109,   111,
     0,    32,     0,   115,    23,    24,    25,    26,    32,    28,
    29,    30,    31,    36,    37,    12,     0,   182,     0,     0,
   129,   128,     0,     0,   143,   142,     0,     0,     0,     0,
    74,    75,    90,     0,    91,   101,   106,   100,   113,    87,
    88,     0,     0,     0,     0,     0,     0,     0,   147,   155,
   151,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,   173,   171,    71,    73,     0,
   110,    38,    32,     0,    27,   179,     0,     0,   130,     0,
   119,    92,    93,    94,     0,   114,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    19,    72,   112,     0,
     0,    17,     0,   176,   121,    32,    51,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,   169,   168,     0,     0,     0,
    34,   117,   180,   184,    17,    32,     0,   144,   145,   148,
   149,   153,   154,   152,   156,   157,   158,   159,   150,   146,
   161,     0,   162,   164,   165,   163,     0,     0,    17,     0,
    32,     0,   177,     0,   120,     0,     0,     0,    20,    17,
     0,   181,     0,   122,   160,   166,   167,    35,   118,   178,
     0,     0
};

static const short yydefgoto[] = {    17,
    18,    19,    29,    41,   101,   330,   117,   193,   360,   171,
   172,    86,    20,    21,    42,    43,    97,   108,    45,   223,
    88,    89,   173,    90,   327,    92,   174,    47,    93,   191,
    49,    50,   264,   361,    51,   306,   336,    52,    53,    54,
    55,    56,   143,    57,    94,    59,    60,    61,    62,    63,
    64,    65,    66,    67,   328,    68,   105,   106,    28,    24,
   335,   373,   302,   362,   141,   267
};

static const short yypact[] = {  1198,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   -50,-32768,   850,-32768,-32768,-32768,
-32768,   -16,-32768,-32768,-32768,-32768,-32768,   -65,  1113,   -35,
   -57,   -28,   -25,   -14,    -9,   991,    30,   991,   335,-32768,
    -8,    33,    -1,   -46,  1113,     3,  1113,    -4,  1096,  1113,
  1113,     6,  1113,  1113,  1113,  1113,  1113,    22,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,  1113,  1212,    33,
   991,   991,   -21,-32768,-32768,-32768,-32768,-32768,    18,    31,
    34,-32768,   991,    28,-32768,    21,    13,   -52,  1181,    74,
    43,  1015,    35,    37,-32768,    45,-32768,-32768,-32768,    44,
    48,-32768,-32768,    25,    47,    46,   991,-32768,-32768,   991,
-32768,   877,-32768,-32768,    50,-32768,    53,  1096,  1096,  1096,
  1096,    52,  1096,  1096,  1096,  1096,  1096,  1096,-32768,-32768,
  1113,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    32,   100,
    72,    75,    77,    94,    76,   101,   102,   103,    28,    28,
    28,    95,-32768,   -43,   107,   -43,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   991,   105,   991,   108,-32768,-32768,   -43,   -43,
  1260,-32768,  1113,   991,-32768,    33,   110,   104,-32768,   109,
   112,  1096,   111,    79,-32768,-32768,-32768,-32768,  1096,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   114,   113,    91,    33,
-32768,-32768,   118,   120,-32768,-32768,   121,   124,   125,   991,
-32768,-32768,-32768,   126,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   127,   128,   129,   130,   131,   133,   136,-32768,-32768,
-32768,   137,   138,   140,   141,   142,   144,   145,   146,   147,
   148,   149,   152,   154,    92,-32768,-32768,    -1,-32768,   991,
-32768,-32768,  1096,    93,-32768,-32768,   158,   165,-32768,   167,
-32768,-32768,-32768,-32768,   159,-32768,   991,   991,   991,   991,
   991,   991,   991,   991,   991,   991,   991,   991,   991,   204,
   206,   991,   991,   991,   899,   899,-32768,-32768,-32768,   139,
   169,  1113,  1075,-32768,-32768,  1096,-32768,   172,   174,   176,
   177,   178,   179,   180,   181,   182,   183,   184,   185,   187,
   -54,   189,   193,   199,   200,-32768,-32768,   164,   196,   203,
-32768,-32768,-32768,-32768,  1113,  1096,   205,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   243,-32768,-32768,-32768,-32768,   899,   899,  1113,   207,
  1096,   208,-32768,   210,-32768,   211,   212,   215,-32768,  1113,
   216,-32768,   217,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   267,-32768
};

static const short yypgoto[] = {-32768,
   263,-32768,-32768,   352,-32768,-32768,   721,-32768,-32768,-32768,
-32768,   209,-32768,-32768,     4,-32768,   -27,    23,   307,  -102,
    11,   -79,   198,-32768,   723,-32768,-32768,   319,   166,    36,
-32768,   330,-32768,-32768,   366,-32768,-32768,   422,   460,     0,
   471,   482,    73,   612,   202,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,  -282,   628,   115,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,    -5,-32768
};


#define	YYLAST		1308


static const short yytable[] = {    23,
    95,    44,   -76,    22,   153,    27,   351,   112,    87,    25,
   -76,   352,   178,   329,   104,   156,    23,    44,    30,    44,
    22,    44,    44,    44,    69,    44,    44,    44,    44,    44,
    74,    75,    76,    77,    78,   109,    83,   110,    70,    46,
    44,    71,   142,    72,   145,   221,   222,    96,   124,    31,
    73,    95,   102,   225,   103,    46,   107,    46,   114,    46,
    46,    46,   112,    46,    46,    46,    46,    46,   131,   217,
   218,   219,   140,   149,   367,   368,   230,   231,    46,    79,
    80,    81,    35,   148,   137,    83,   150,    37,   154,   151,
    44,    44,    44,    44,   155,    44,    44,    44,    44,    44,
    44,   176,   179,    44,   180,   181,   182,   183,   184,   185,
    84,   186,   192,   194,   199,    85,   207,   124,   124,   124,
   124,   208,   124,   124,   124,   124,   124,   124,    46,    46,
    46,    46,   209,    46,    46,    46,    46,    46,    46,   211,
   210,    46,   158,   159,   160,   161,   162,   163,   164,   165,
   166,   167,   168,   169,   170,    44,   212,   213,   104,   214,
   220,   227,   215,   216,    44,   224,   259,   229,   258,  -116,
   263,    44,   261,   266,   260,   268,   270,   272,  -183,   271,
   273,   274,   142,   301,   297,   276,   277,   278,   279,   280,
   281,   124,   282,    46,    48,   283,   284,   285,   124,   286,
   287,   288,    46,   289,   290,   291,   292,   293,   294,    46,
    48,   295,    48,   296,    48,    48,    48,   307,    48,    48,
    48,    48,    48,   303,   304,   321,   305,   322,   332,   357,
    58,   331,   338,    48,   339,    44,   340,   341,   342,   343,
   344,   345,   346,   347,   348,   349,    58,   350,    58,   353,
    58,    58,    58,   354,    58,    58,    58,    58,    58,   355,
   356,   358,   124,   359,   366,   365,   382,   370,   372,    58,
   374,   375,   376,    46,    44,   377,   379,   380,    44,    26,
   298,   147,   269,    48,    48,    48,    48,   175,    48,    48,
    48,    48,    48,    48,     0,   299,    48,   334,     0,     0,
   257,     0,     0,     0,     0,   124,   140,    44,    44,     0,
     0,     0,    46,     0,     0,     0,    46,     0,     0,    58,
    58,    58,    58,     0,    58,    58,    58,    58,    58,    58,
     0,    44,    58,    44,     0,   124,     0,    74,    75,    76,
    77,    78,    44,     0,     0,    46,    46,     0,    48,     0,
     0,     0,     0,     0,     0,   118,    31,    48,     0,     0,
   124,     0,     0,     0,    48,     0,     0,   119,     0,    46,
     0,    46,     0,     0,     0,     0,     0,     0,   120,     0,
    46,     0,     0,     0,    58,     0,    79,    80,    81,    35,
    82,     0,    83,    58,    37,     0,   111,    99,   113,     0,
    58,   129,   130,     0,   132,   133,   134,   135,   136,     0,
     0,     0,     0,     0,   121,     0,     0,    84,     0,   138,
     0,     0,    85,     0,   118,   118,   118,   118,    48,   118,
   118,   118,   118,   118,   118,     0,   119,   119,   119,   119,
     0,   119,   119,   119,   119,   119,   119,   120,   120,   120,
   120,     0,   120,   120,   120,   120,   120,   120,     0,     0,
     0,     0,     0,     0,    58,     0,     0,    48,     0,     0,
   122,    48,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,   206,   121,   121,   121,   121,     0,   121,   121,
   121,   121,   121,   121,     0,     0,     0,     0,   118,     0,
    48,    48,     0,    58,     0,   118,     0,    58,   123,     0,
   119,     0,     0,     0,     0,     0,     0,   119,     0,   125,
     0,   120,     0,     0,    48,     0,    48,     0,   120,     0,
   126,     0,     0,     0,   255,    48,    58,    58,     0,   122,
   122,   122,   122,     0,   122,   122,   122,   122,   122,   122,
     0,     0,     0,     0,     0,     0,     0,   121,     0,     0,
    58,     0,    58,     0,   121,     0,     0,     0,     0,   118,
     0,    58,     0,     0,     0,     0,     0,   123,   123,   123,
   123,   119,   123,   123,   123,   123,   123,   123,   125,   125,
   125,   125,   120,   125,   125,   125,   125,   125,   125,   126,
   126,   126,   126,     0,   126,   126,   126,   126,   126,   126,
     0,     0,   118,   122,     0,     0,     0,     0,     0,     0,
   122,     0,     0,     0,   119,     0,     0,     0,   121,     0,
     0,     0,     0,     0,     0,   120,     0,     0,     0,     0,
     0,     0,   118,     0,     0,     0,     0,     0,     0,     0,
     0,   123,     0,   333,   119,     0,     0,     0,   123,     0,
   127,     0,   125,     0,     0,   120,     0,   118,     0,   125,
     0,   121,     0,   126,     0,     0,   128,     0,     0,   119,
   126,     0,     0,     0,   122,     0,   363,     0,     0,     0,
   120,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,   121,     0,     0,     0,     0,     0,     0,     0,     0,
   369,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,   378,   123,     0,     0,     0,   121,   122,     0,   127,
   127,   127,   127,   125,   127,   127,   127,   127,   127,   127,
     0,     0,     0,     0,   126,   128,   128,   128,   128,     0,
   128,   128,   128,   128,   128,   128,     0,   122,    91,     0,
    98,   100,     0,     0,     0,   123,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,   125,     0,     0,     0,
     0,     0,   122,     0,     0,     0,     0,   126,     0,     0,
     0,     0,     0,   144,   146,   123,     0,     0,     0,     0,
     0,     0,     0,   127,     0,   152,   125,     0,     0,     0,
   127,     0,     0,     0,     0,     0,     0,   126,     0,   128,
   123,     0,     0,     0,     0,     0,   128,     0,     0,   187,
     0,   125,   188,     0,   190,     0,     0,     0,   195,   196,
   197,   198,   126,   200,   201,   202,   203,   204,   205,   381,
     0,     0,     0,     0,     0,     0,     0,     1,     2,     3,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    14,     0,     0,     0,   127,     0,     0,     0,     0,    74,
    75,    76,    77,    78,     0,     0,     0,     0,     0,     0,
   128,     0,     0,     0,     0,   226,     0,   228,    31,     0,
    15,    74,    75,    76,    77,    78,   256,     0,     0,     0,
     0,     0,   262,     0,     0,     0,     0,   127,     0,   265,
    31,     0,     0,     0,     0,     0,     0,     0,    79,    80,
    81,    35,    82,   128,    83,    16,    37,   189,     0,     0,
     0,     0,   275,     0,     0,     0,     0,   127,     0,     0,
    79,    80,    81,    35,    82,     0,    83,     0,    37,    84,
     0,     0,     0,   128,    85,     0,     0,     0,     0,     0,
     0,     0,   127,     0,     0,     0,     0,     0,     0,     0,
     0,    84,   190,   300,     0,   326,    85,     0,   128,     0,
     0,     0,     0,    74,    75,    76,    77,    78,     0,   308,
   309,   310,   311,   312,   313,   314,   315,   316,   317,   318,
   319,   320,    31,     0,   323,   324,   325,    74,    75,    76,
    77,    78,     0,     0,     0,     0,   337,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    31,     0,     0,     0,
     0,     0,    79,    80,    81,    35,    82,     0,    83,     0,
    37,     0,     0,     0,     0,     0,   364,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    79,    80,    81,    35,
   177,     0,    83,    84,    37,     0,     0,     0,    85,     0,
     0,   371,     1,     2,     3,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    13,    14,     0,    84,     0,     0,
     0,     0,    85,     1,     2,     3,     4,     5,     6,     7,
     8,     9,    10,    11,    12,    13,    14,    31,    32,    33,
     1,     2,     3,     4,     5,     6,     7,     8,     9,    10,
    11,    12,    13,    14,    31,    32,    33,     0,     0,     0,
     0,     0,     0,     0,    34,   115,     0,     0,     0,     0,
    35,     0,     0,    36,     0,    37,     0,     0,     0,     0,
     0,    34,     0,     0,     0,     0,     0,    35,     0,     0,
    36,     0,    37,     0,     0,     0,     0,     0,    38,     0,
    39,    16,     0,     0,     0,     0,     0,   116,     0,     0,
     0,     0,     0,     0,     0,    38,     0,    39,    16,     0,
     0,     0,     0,     0,    40,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,     1,
     2,     3,     4,     5,     6,     7,     8,     9,    10,    11,
    12,    13,    14,     0,     0,     0,     0,   157,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    15,   158,
   159,   160,   161,   162,   163,   164,   165,   166,   167,   168,
   169,   170,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,   139,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    16,   232,   233,   234,   235,   236,   237,
   238,   239,   240,   241,   242,   243,   244,   245,   246,   247,
     0,   248,   249,   250,   251,   252,   253,   254
};

static const short yycheck[] = {     0,
    22,    29,    60,     0,    84,    22,    61,    60,    36,    60,
    68,    66,    92,   296,    42,    68,    17,    45,    84,    47,
    17,    49,    50,    51,    60,    53,    54,    55,    56,    57,
     3,     4,     5,     6,     7,    82,    58,    84,    67,    29,
    68,    67,    70,    58,    72,    89,    90,    37,    49,    22,
    60,    22,    61,   156,    22,    45,    58,    47,    63,    49,
    50,    51,    60,    53,    54,    55,    56,    57,    63,   149,
   150,   151,    69,    56,   357,   358,   179,   180,    68,    52,
    53,    54,    55,    73,    63,    58,    56,    60,    68,    56,
   118,   119,   120,   121,    82,   123,   124,   125,   126,   127,
   128,    59,    68,   131,    68,    61,    63,    60,    84,    63,
    83,    66,    63,    61,    63,    88,    85,   118,   119,   120,
   121,    22,   123,   124,   125,   126,   127,   128,   118,   119,
   120,   121,    61,   123,   124,   125,   126,   127,   128,    63,
    66,   131,    69,    70,    71,    72,    73,    74,    75,    76,
    77,    78,    79,    80,    81,   183,    63,    82,   186,    59,
    66,    57,    61,    61,   192,    59,    63,    60,    59,    91,
    60,   199,    61,    60,    66,    85,    59,    57,    66,    60,
    57,    57,   210,    91,    93,    60,    60,    60,    60,    60,
    60,   192,    60,   183,    29,    60,    60,    60,   199,    60,
    60,    60,   192,    60,    60,    60,    60,    60,    60,   199,
    45,    60,    47,    60,    49,    50,    51,    59,    53,    54,
    55,    56,    57,    66,    60,    22,    60,    22,    60,    66,
    29,    93,    61,    68,    61,   263,    61,    61,    61,    61,
    61,    61,    61,    61,    61,    61,    45,    61,    47,    61,
    49,    50,    51,    61,    53,    54,    55,    56,    57,    61,
    61,    66,   263,    61,    22,    61,     0,    61,    61,    68,
    61,    61,    61,   263,   302,    61,    61,    61,   306,    17,
   258,    73,   210,   118,   119,   120,   121,    90,   123,   124,
   125,   126,   127,   128,    -1,   260,   131,   303,    -1,    -1,
   186,    -1,    -1,    -1,    -1,   306,   303,   335,   336,    -1,
    -1,    -1,   302,    -1,    -1,    -1,   306,    -1,    -1,   118,
   119,   120,   121,    -1,   123,   124,   125,   126,   127,   128,
    -1,   359,   131,   361,    -1,   336,    -1,     3,     4,     5,
     6,     7,   370,    -1,    -1,   335,   336,    -1,   183,    -1,
    -1,    -1,    -1,    -1,    -1,    49,    22,   192,    -1,    -1,
   361,    -1,    -1,    -1,   199,    -1,    -1,    49,    -1,   359,
    -1,   361,    -1,    -1,    -1,    -1,    -1,    -1,    49,    -1,
   370,    -1,    -1,    -1,   183,    -1,    52,    53,    54,    55,
    56,    -1,    58,   192,    60,    -1,    45,    63,    47,    -1,
   199,    50,    51,    -1,    53,    54,    55,    56,    57,    -1,
    -1,    -1,    -1,    -1,    49,    -1,    -1,    83,    -1,    68,
    -1,    -1,    88,    -1,   118,   119,   120,   121,   263,   123,
   124,   125,   126,   127,   128,    -1,   118,   119,   120,   121,
    -1,   123,   124,   125,   126,   127,   128,   118,   119,   120,
   121,    -1,   123,   124,   125,   126,   127,   128,    -1,    -1,
    -1,    -1,    -1,    -1,   263,    -1,    -1,   302,    -1,    -1,
    49,   306,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,   131,   118,   119,   120,   121,    -1,   123,   124,
   125,   126,   127,   128,    -1,    -1,    -1,    -1,   192,    -1,
   335,   336,    -1,   302,    -1,   199,    -1,   306,    49,    -1,
   192,    -1,    -1,    -1,    -1,    -1,    -1,   199,    -1,    49,
    -1,   192,    -1,    -1,   359,    -1,   361,    -1,   199,    -1,
    49,    -1,    -1,    -1,   183,   370,   335,   336,    -1,   118,
   119,   120,   121,    -1,   123,   124,   125,   126,   127,   128,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,   192,    -1,    -1,
   359,    -1,   361,    -1,   199,    -1,    -1,    -1,    -1,   263,
    -1,   370,    -1,    -1,    -1,    -1,    -1,   118,   119,   120,
   121,   263,   123,   124,   125,   126,   127,   128,   118,   119,
   120,   121,   263,   123,   124,   125,   126,   127,   128,   118,
   119,   120,   121,    -1,   123,   124,   125,   126,   127,   128,
    -1,    -1,   306,   192,    -1,    -1,    -1,    -1,    -1,    -1,
   199,    -1,    -1,    -1,   306,    -1,    -1,    -1,   263,    -1,
    -1,    -1,    -1,    -1,    -1,   306,    -1,    -1,    -1,    -1,
    -1,    -1,   336,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,   192,    -1,   302,   336,    -1,    -1,    -1,   199,    -1,
    49,    -1,   192,    -1,    -1,   336,    -1,   361,    -1,   199,
    -1,   306,    -1,   192,    -1,    -1,    49,    -1,    -1,   361,
   199,    -1,    -1,    -1,   263,    -1,   335,    -1,    -1,    -1,
   361,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,   336,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
   359,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,   370,   263,    -1,    -1,    -1,   361,   306,    -1,   118,
   119,   120,   121,   263,   123,   124,   125,   126,   127,   128,
    -1,    -1,    -1,    -1,   263,   118,   119,   120,   121,    -1,
   123,   124,   125,   126,   127,   128,    -1,   336,    36,    -1,
    38,    39,    -1,    -1,    -1,   306,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,   306,    -1,    -1,    -1,
    -1,    -1,   361,    -1,    -1,    -1,    -1,   306,    -1,    -1,
    -1,    -1,    -1,    71,    72,   336,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,   192,    -1,    83,   336,    -1,    -1,    -1,
   199,    -1,    -1,    -1,    -1,    -1,    -1,   336,    -1,   192,
   361,    -1,    -1,    -1,    -1,    -1,   199,    -1,    -1,   107,
    -1,   361,   110,    -1,   112,    -1,    -1,    -1,   118,   119,
   120,   121,   361,   123,   124,   125,   126,   127,   128,     0,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,     8,     9,    10,
    11,    12,    13,    14,    15,    16,    17,    18,    19,    20,
    21,    -1,    -1,    -1,   263,    -1,    -1,    -1,    -1,     3,
     4,     5,     6,     7,    -1,    -1,    -1,    -1,    -1,    -1,
   263,    -1,    -1,    -1,    -1,   173,    -1,   175,    22,    -1,
    51,     3,     4,     5,     6,     7,   184,    -1,    -1,    -1,
    -1,    -1,   192,    -1,    -1,    -1,    -1,   306,    -1,   199,
    22,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    52,    53,
    54,    55,    56,   306,    58,    86,    60,    61,    -1,    -1,
    -1,    -1,   220,    -1,    -1,    -1,    -1,   336,    -1,    -1,
    52,    53,    54,    55,    56,    -1,    58,    -1,    60,    83,
    -1,    -1,    -1,   336,    88,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,   361,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    83,   260,   263,    -1,    87,    88,    -1,   361,    -1,
    -1,    -1,    -1,     3,     4,     5,     6,     7,    -1,   277,
   278,   279,   280,   281,   282,   283,   284,   285,   286,   287,
   288,   289,    22,    -1,   292,   293,   294,     3,     4,     5,
     6,     7,    -1,    -1,    -1,    -1,   306,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    22,    -1,    -1,    -1,
    -1,    -1,    52,    53,    54,    55,    56,    -1,    58,    -1,
    60,    -1,    -1,    -1,    -1,    -1,   336,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    52,    53,    54,    55,
    56,    -1,    58,    83,    60,    -1,    -1,    -1,    88,    -1,
    -1,   361,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    -1,    83,    -1,    -1,
    -1,    -1,    88,     8,     9,    10,    11,    12,    13,    14,
    15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
     8,     9,    10,    11,    12,    13,    14,    15,    16,    17,
    18,    19,    20,    21,    22,    23,    24,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    49,    50,    -1,    -1,    -1,    -1,
    55,    -1,    -1,    58,    -1,    60,    -1,    -1,    -1,    -1,
    -1,    49,    -1,    -1,    -1,    -1,    -1,    55,    -1,    -1,
    58,    -1,    60,    -1,    -1,    -1,    -1,    -1,    83,    -1,
    85,    86,    -1,    -1,    -1,    -1,    -1,    92,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    83,    -1,    85,    86,    -1,
    -1,    -1,    -1,    -1,    92,     8,     9,    10,    11,    12,
    13,    14,    15,    16,    17,    18,    19,    20,    21,     8,
     9,    10,    11,    12,    13,    14,    15,    16,    17,    18,
    19,    20,    21,    -1,    -1,    -1,    -1,    57,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    51,    69,
    70,    71,    72,    73,    74,    75,    76,    77,    78,    79,
    80,    81,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    61,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    86,    25,    26,    27,    28,    29,    30,
    31,    32,    33,    34,    35,    36,    37,    38,    39,    40,
    -1,    42,    43,    44,    45,    46,    47,    48
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 6:
#line 65 "new.y"
{is_func_bool = true; current_pointer++;  curr_scopes[current_pointer]++;;
    break;}
case 7:
#line 65 "new.y"
{is_func_bool = false;current_pointer--;;
    break;}
case 17:
#line 77 "new.y"
{;
    break;}
case 18:
#line 78 "new.y"
{ current_pointer++;  curr_scopes[current_pointer]++; ;
    break;}
case 19:
#line 78 "new.y"
{current_pointer--; ;
    break;}
case 32:
#line 92 "new.y"
{;
    break;}
case 33:
#line 93 "new.y"
{ current_pointer++;  curr_scopes[current_pointer]++; ;
    break;}
case 34:
#line 93 "new.y"
{current_pointer--; ;
    break;}
case 52:
#line 118 "new.y"
{insert_type();;
    break;}
case 53:
#line 119 "new.y"
{insert_type();;
    break;}
case 54:
#line 120 "new.y"
{insert_type();;
    break;}
case 55:
#line 121 "new.y"
{insert_type();;
    break;}
case 56:
#line 124 "new.y"
{insert_type();;
    break;}
case 57:
#line 125 "new.y"
{insert_type();;
    break;}
case 58:
#line 126 "new.y"
{insert_type();;
    break;}
case 59:
#line 127 "new.y"
{insert_type();;
    break;}
case 60:
#line 128 "new.y"
{insert_type();;
    break;}
case 61:
#line 129 "new.y"
{insert_type();;
    break;}
case 62:
#line 130 "new.y"
{insert_type();;
    break;}
case 63:
#line 131 "new.y"
{insert_type();;
    break;}
case 64:
#line 132 "new.y"
{insert_type();;
    break;}
case 65:
#line 133 "new.y"
{insert_type();;
    break;}
case 68:
#line 142 "new.y"
{ 
                       if(is_func_bool){
                        
                        var_records* rec = new var_records{yyvsp[0].string, type,convert_scope_to_string()};
                        var_list.push_back(rec);
                        }
                       else{
                         add('V');
                       }
                     ;
    break;}
case 76:
#line 170 "new.y"
{add('V');;
    break;}
case 113:
#line 229 "new.y"
{ current_pointer++;  curr_scopes[current_pointer]++; ;
    break;}
case 114:
#line 230 "new.y"
{ current_pointer++;  curr_scopes[current_pointer]++; ;
    break;}
case 115:
#line 234 "new.y"
{current_pointer--; ;
    break;}
case 116:
#line 235 "new.y"
{current_pointer--; ;
    break;}
case 117:
#line 235 "new.y"
{ current_pointer++;  curr_scopes[current_pointer]++; ;
    break;}
case 118:
#line 235 "new.y"
{current_pointer--; ;
    break;}
case 119:
#line 240 "new.y"
{ current_pointer++;  curr_scopes[current_pointer]++; ;
    break;}
case 120:
#line 240 "new.y"
{current_pointer--; ;
    break;}
case 121:
#line 241 "new.y"
{ current_pointer++;  curr_scopes[current_pointer]++; ;
    break;}
case 122:
#line 241 "new.y"
{current_pointer--; ;
    break;}
case 175:
#line 354 "new.y"
{add('F'); is_func_bool = true;;
    break;}
case 176:
#line 356 "new.y"
{current_pointer++;  curr_scopes[current_pointer]++; ;
    break;}
case 177:
#line 357 "new.y"
{   new_func_entry( yyvsp[-8].string, yyvsp[-9].string, par_list.size(), par_list, var_list);
                var_list.clear(); 
                par_list.clear();
                ;
    break;}
case 178:
#line 361 "new.y"
{is_func_bool = false;current_pointer--; ;
    break;}
case 179:
#line 362 "new.y"
{current_pointer++;  curr_scopes[current_pointer]++;;
    break;}
case 180:
#line 363 "new.y"
{
                    new_func_entry( yyvsp[-7].string, yyvsp[-8].string, par_list.size(), par_list, var_list); 
                    var_list.clear(); 
                    par_list.clear();
                ;
    break;}
case 181:
#line 368 "new.y"
{is_func_bool = false;current_pointer--; ;
    break;}
case 182:
#line 372 "new.y"
{
            par_records* rec = new par_records{yyvsp[0].string, yyvsp[-1].string};
            par_list.push_back(rec);
        ;
    break;}
case 183:
#line 377 "new.y"
{
            par_records* rec = new par_records{yyvsp[0].string, yyvsp[-1].string};
            par_list.push_back(rec);
          ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 386 "new.y"


void yyerror(char* s){
	printf("Syntax Error : In line number %d\n",yylineno);
	fprintf(parsefile," %s\n",s);
}

int main(int argc ,char * argv[]){
    char inp_file[100],tok[100],parse[100];

    sprintf(inp_file,"inp.phic");

    yyin = fopen(inp_file,"r");

  construct_stack();
	int i = yyparse();

    print_table();
    print_function_table();

	if(i) printf("Failure\n");
	else printf("Success\n");

	return 0;
}
